-- auto-generated definition
create table sku
(
    id                         int auto_increment
        primary key,
    createdAt                  datetime default CURRENT_TIMESTAMP null,
    name                       varchar(1000)                      null,
    skuId                      varchar(100)                       null,
    eanCode                    varchar(100)                       null,
    kind                       varchar(10)                        null,
    unitName                   varchar(10)                        null,
    material                   varchar(100)                       null,
    referenceQuoteAmountInYuan decimal(15, 5)                     null,
    nameInInvoice              varchar(100)                       null comment '报关名/报关单位',
    productDeliveryDays        int                                null comment '采购交期',
    spuId                      varchar(100)                       null,
    brand                      varchar(100)                       null,
    cnName                     varchar(1000)                      null,
    categoryName               varchar(100)                       null,
    enNameInInvoice            varchar(100)                       null,
    crucialTags                varchar(1000)                      null,
    productOperationStatus     varchar(1000)                      null comment '运营状态,xxx,xxx',
    timeRelated                varchar(1000)                      null comment '强时间属性,xxx,xxx',
    replacedSKUId              varchar(100)                       null,
    skuSource                  varchar(100)                       null comment '商品归属',
    marketChannel              varchar(100)                       null comment '销售渠道',
    toolantQuotationFactor     decimal(15, 5)                     null comment 'ToolAnt报价系数',
    clearanceLevel             varchar(10)                        null,
    countryCode                varchar(100)                       null comment '第一国家编码',
    subcategory                varchar(100)                       null,
    productLine                varchar(100)                       null,
    productSeries              varchar(100)                       null,
    supplyPartnerName          varchar(100)                       null,
    mainSupplierName           varchar(100)                       null,
    mainSupplierShortName      varchar(100)                       null,
    mainSupplierCode           varchar(100)                       null,
    isUnavailable              char                               null,
    specialClearing            char                               null,
    firstSaleDate              varchar(100)                       null,
    constraint skuId
        unique (skuId)
);

create index idx_spu
    on sku (spuId);

-- auto-generated definition
create table openapi_deal_full
(
    id                  int auto_increment
        primary key,
    createdAt           datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    boutiqueAsinUrl     varchar(1000)                      null,
    conversionRate      double                             null,
    currencyCode        varchar(10)                        null,
    dealFee             varchar(100)                       null,
    dealFeeAmount       json                               null,
    dealId              varchar(100)                       null,
    dealType            varchar(100)                       null,
    endDate             varchar(100)                       null,
    eventName           varchar(100)                       null,
    feeRate             double                             null,
    firstSyncTime       varchar(100)                       null,
    glanceViews         int                                null,
    internalDescription varchar(1000)                      null,
    latestSyncTime      varchar(100)                       null,
    marketId            varchar(100)                       null,
    marketName          varchar(100)                       null,
    quantity            int                                null,
    sales               int                                null,
    salesAmount         json                               null,
    salesRate           double                             null,
    startDate           varchar(100)                       null,
    status              varchar(100)                       null,
    timeReminder        varchar(100)                       null,
    unitSales           int                                null
);

create index idx_dealId
    on openapi_deal_full (dealId);

create index idx_marketId
    on openapi_deal_full (marketId);

-- auto-generated definition
create table openapi_deal_order_full
(
    id              int auto_increment
        primary key,
    createdAt       datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    pid             varchar(100)                       null comment '活动 id, deal id',
    marketId        varchar(100)                       null,
    orderStatus     varchar(10)                        null,
    orderId         varchar(100)                       null,
    asin            varchar(100)                       null,
    title           varchar(1000)                      null,
    msku            varchar(100)                       null,
    quantityOrdered int                                null,
    itemPrice       decimal(15, 5)                     null,
    itemPriceAmount json                               null,
    purchaseDate    varchar(100)                       null
);

create index idx_dealId
    on openapi_deal_order_full (pid);

create index idx_marketId
    on openapi_deal_order_full (marketId);

create index idx_msku
    on openapi_deal_order_full (msku);

-- auto-generated definition
create table openapi_delivery_detail_full
(
    id                          int auto_increment
        primary key,
    createdAt                   datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    country                     varchar(10)                        null,
    confirmShipmentDate         varchar(100)                       null,
    inboundDate                 varchar(100)                       null,
    memo                        varchar(500)                       null,
    confirmShipmentPerson       varchar(100)                       null,
    payer                       varchar(100)                       null,
    erpCreatedAt                varchar(100)                       null,
    trackings                   varchar(100)                       null,
    payment                     double                             null,
    state                       tinyint                            null,
    createrId                   varchar(100)                       null,
    deliveryCode                varchar(100)                       null,
    actualArrivalDate           varchar(100)                       null,
    receiptMemo                 varchar(500)                       null,
    importCompanyName           varchar(100)                       null,
    arrivalWarehouseId          int                                null,
    arrivalSupplierId           int                                null,
    rnType                      int                                null,
    receiptDate                 varchar(100)                       null,
    weight                      double                             null,
    arrivalDate                 varchar(100)                       null,
    importCompany               varchar(100)                       null,
    diffHandlerId               int                                null,
    creater                     varchar(100)                       null,
    transportMode               varchar(100)                       null,
    flagLogisticsFee            tinyint                            null,
    status                      varchar(100)                       null,
    code                        varchar(100)                       null,
    forecastLogisticsCurrency   varchar(10)                        null,
    box                         int                                null,
    supplierCode                varchar(100)                       null,
    countryId                   tinyint                            null,
    expectArrivalDate           varchar(100)                       null,
    expectShipmentDate          varchar(100)                       null,
    customsClearance            varchar(100)                       null,
    custom1                     varchar(100)                       null,
    shipmentDate                varchar(100)                       null,
    custom2                     varchar(100)                       null,
    channelId                   int                                null,
    containerType               varchar(100)                       null,
    deliveryType                varchar(100)                       null,
    warehouses                  json                               null,
    diffHandleTime              varchar(100)                       null,
    updateTime                  varchar(100)                       null,
    transport                   varchar(100)                       null,
    overReceiptReason           varchar(100)                       null,
    flagSecondCostHedge         tinyint                            null,
    shipmentIds                 json                               null,
    item_relevanceItemId        int                                null,
    item_confirmShipmentDate    varchar(100)                       null,
    item_fnsku                  varchar(100)                       null,
    item_totalHandleQuantity    int                                null,
    item_singleQuantity         int                                null,
    item_memo                   varchar(100)                       null,
    item_purchasePrice          decimal(15, 5)                     null,
    item_type                   varchar(10)                        null,
    item_lostQuantity           int                                null,
    item_kingdeeReceiptQuantity int                                null,
    item_compensateQuantity     int                                null,
    item_adjustmentQuantity     int                                null,
    item_kingdeeReceiptQty      int                                null,
    item_id                     int                                null,
    item_sku                    varchar(100)                       null,
    item_deliveryCode           varchar(100)                       null,
    item_skuTypeName            varchar(100)                       null,
    item_msku                   varchar(100)                       null,
    item_relevanceCode          varchar(100)                       null,
    item_destinationCountry     varchar(10)                        null,
    item_unit                   varchar(10)                        null,
    item_warehouseId            int                                null,
    item_alreadyMatchQuantity   int                                null,
    item_flag                   tinyint(1)                         null,
    item_receiptQuantity        int                                null,
    item_creatorId              int                                null,
    item_additionalQuantity     int                                null,
    item_diffQuantity           int                                null,
    item_purchaseCurrency       varchar(10)                        null,
    item_warehouseName          varchar(100)                       null,
    item_categoryName           varchar(100)                       null,
    item_expectArrivalDate      varchar(100)                       null,
    item_marketId               int                                null,
    item_skuName                varchar(500)                       null,
    item_shipmentItemMappingId  varchar(100)                       null,
    item_purchaseCurrencySymbol varchar(10)                        null,
    item_arrivalMarketId        int                                null,
    item_quantity               int                                null,
    item_updateTime             varchar(100)                       null,
    item_skuType                varchar(100)                       null,
    item_marketName             varchar(100)                       null,
    item_flCode                 varchar(100)                       null,
    item_createTime             varchar(100)                       null,
    item_handleDiffQuantity     int                                null,
    item_shipmentId             varchar(100)                       null,
    item_asin                   varchar(100)                       null,
    item_category               varchar(100)                       null,
    item_shipmentName           varchar(100)                       null,
    diffApproveUserId           varchar(100)                       null,
    forecastLogisticsCost       double                             null
);

create index idx_deliveryCode
    on openapi_delivery_detail_full (deliveryCode);

create index idx_mkt
    on openapi_delivery_detail_full (item_marketId);

create index idx_msku
    on openapi_delivery_detail_full (item_msku);

-- auto-generated definition
create table openapi_delivery_full
(
    id                        int auto_increment
        primary key,
    createdAt                 datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    actualAmount              decimal(15, 5)                     null,
    actualAmountTime          varchar(100)                       null,
    actualArrivalDate         varchar(100)                       null,
    actualArrivePortDate      varchar(100)                       null,
    actualCurrencyCode        varchar(100)                       null,
    actualCurrencySymbol      varchar(100)                       null,
    aliAccountId              int                                null,
    aliOrderNo                varchar(100)                       null,
    arrivalWarehouseId        int                                null,
    attachments               json                               null,
    box                       int                                null,
    cancelActualFee           tinyint(1)                         null,
    channelId                 int                                null,
    chargeUnitPrice           decimal(15, 5)                     null,
    chargeUnitPriceUnit       varchar(100)                       null,
    chargeUnitPriceUnitSymbol varchar(100)                       null,
    chargeWeight              double                             null,
    chargeWeightUnit          varchar(100)                       null,
    cnWarehouse               tinyint(1)                         null,
    code                      varchar(100)                       null,
    confirmShipmentDate       varchar(100)                       null,
    containerType             varchar(100)                       null,
    country                   varchar(100)                       null,
    erpCreatedAt              varchar(100)                       null,
    createdTime               varchar(100)                       null,
    creator                   varchar(100)                       null,
    custom1                   varchar(100)                       null,
    custom2                   varchar(100)                       null,
    customsClearance          varchar(100)                       null,
    diffApproveStatus         varchar(100)                       null,
    diffApproveStatusName     varchar(100)                       null,
    diffApproveUserId         varchar(100)                       null,
    diffHandleTime            varchar(100)                       null,
    diffHandler               varchar(100)                       null,
    diffHandlerId             int                                null,
    diffQuantity              int                                null,
    diffReviewId              varchar(100)                       null,
    dlBusinessName            varchar(100)                       null,
    dlBusinessType            varchar(100)                       null,
    estimateArrivePortDate    varchar(100)                       null,
    estimatedAmount           decimal(15, 5)                     null,
    estimatedAmountTime       varchar(100)                       null,
    estimatedCurrencyCode     varchar(100)                       null,
    estimatedCurrencySymbol   varchar(100)                       null,
    etaRedFlag                tinyint(1)                         null,
    expectArrivalDate         varchar(100)                       null,
    expectShipmentDate        varchar(100)                       null,
    fbaWarehouse              tinyint(1)                         null,
    flCodeList                json                               null,
    flagLogisticsFee          tinyint(1)                         null,
    flagSecondCostHedge       tinyint(1)                         null,
    forecastLogisticsCurrency varchar(10)                        null,
    fromWarehouseNames        json                               null,
    fromWarehouseType         varchar(100)                       null,
    handleDiffQuantity        int                                null,
    erpId                     int                                null,
    ifBop                     tinyint(1)                         null,
    ifDiffApprove             tinyint(1)                         null,
    ifPurchaseSplit           tinyint(1)                         null,
    importCompany             varchar(100)                       null,
    importCompanyName         varchar(100)                       null,
    isDealDiffQty             tinyint(1)                         null,
    isShipment                tinyint(1)                         null,
    labelVOS                  json                               null,
    memo                      varchar(100)                       null,
    payer                     varchar(100)                       null,
    quantity                  int                                null,
    receiptDate               varchar(100)                       null,
    receiptQuantity           int                                null,
    receivingAt               varchar(100)                       null,
    relevanceCode             varchar(100)                       null,
    relevanceCodeList         json                               null,
    relevanceItemVos          json                               null,
    sailDate                  varchar(100)                       null,
    shipmentDate              varchar(100)                       null,
    shipmentIdList            json                               null,
    spiltTrackings            json                               null,
    state                     varchar(100)                       null,
    status                    varchar(100)                       null,
    statusName                varchar(100)                       null,
    trackings                 varchar(100)                       null,
    transport                 varchar(100)                       null,
    transportMode             varchar(100)                       null,
    transportName             varchar(100)                       null,
    transportPrescription     varchar(100)                       null,
    transportPrescriptions    json                               null,
    updateFlag                varchar(100)                       null,
    updateTime                varchar(100)                       null,
    volumeWeightCoefficient   float                              null,
    warehouseNames            json                               null,
    warehousePlatform         varchar(100)                       null,
    warehouseType             varchar(100)                       null
);

create index idx_code
    on openapi_delivery_full (code);

-- auto-generated definition
create table openapi_inventory_full
(
    id                        int auto_increment
        primary key,
    createdAt                 datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    addTime                   date                               null,
    arrivedCost               double                             null,
    asin                      varchar(100)                       null,
    assemblyRule              text                               null,
    availableQuantity         int                                null,
    brand                     varchar(100)                       null,
    brandName                 varchar(100)                       null,
    canTransferQuantity       int                                null,
    category                  varchar(100)                       null,
    categoryName              varchar(100)                       null,
    childQuantity             int                                null,
    computePses               tinytext                           null,
    computeYesterday9Pses     tinytext                           null,
    countryListingLevels      json                               null,
    countryListingLevelsStr   tinytext                           null,
    countryListingStates      json                               null,
    countryListingStatesStr   tinytext                           null,
    erpInbound                tinyint(1)                         null,
    erpInboundReceiving       int                                null,
    erpInboundShipped         int                                null,
    erpInboundWaitShipped     int                                null,
    erpInboundWorking         int                                null,
    fbaInboundQuantity        int                                null,
    fbaWarehouse              tinyint(1)                         null,
    fnsku                     varchar(100)                       null,
    goodAvailableQuantity     int                                null,
    erpId                     int                                null,
    inboundAmount             int                                null,
    inboundQuantity           int                                null,
    inboundReceiving          int                                null,
    inboundShipped            int                                null,
    inboundWorking            int                                null,
    inventoryAge0to1Month     int                                null,
    inventoryAge0to3Month     int                                null,
    inventoryAge1to2Month     int                                null,
    inventoryAge2to3Month     int                                null,
    inventoryAge3to6Month     int                                null,
    inventoryAge6to9Month     int                                null,
    inventoryAge9to12Month    int                                null,
    inventoryAge12MonthUp     int                                null,
    inventoryAmount           double                             null,
    inventoryQuantity         int                                null,
    inventoryTotalAmount      double                             null,
    lnQuantity                int                                null,
    msku                      varchar(100)                       null,
    onInventoryAmount         decimal(15, 5)                     null,
    overseasQuantity          int                                null,
    plQuantity                int                                null,
    poQuantity                int                                null,
    productDeliveryDays       int                                null,
    productId                 varchar(100)                       null,
    productManagerAccountId   int                                null,
    productManagerAccountName varchar(100)                       null,
    productState              int                                null,
    productStateName          varchar(100)                       null,
    productType               int                                null,
    productTypeName           varchar(100)                       null,
    ps                        int                                null,
    purchaseCost              double                             null,
    purchaseQuantity          int                                null,
    reservedCustomerOrders    int                                null,
    reservedFCProcessing      int                                null,
    reservedFCTransfer        int                                null,
    reservedQuantity          int                                null,
    shippedTurnover           int                                null,
    reservedUntreated         int                                null,
    singleQuantity            int                                null,
    sku                       varchar(255)                       null,
    skuName                   varchar(100)                       null,
    state                     int                                null,
    stateName                 varchar(100)                       null,
    sum7ps                    int                                null,
    sum15ps                   int                                null,
    sum30ps                   int                                null,
    totalTurnover             int                                null,
    turnover                  int                                null,
    unit                      varchar(100)                       null,
    unsalableAmount           int                                null,
    unsalableQuantity         int                                null,
    unsalableRate             double                             null,
    updateDate                varchar(100)                       null,
    updateTime                varchar(100)                       null,
    waitInboundAmount         int                                null,
    warehouseCountry          varchar(100)                       null,
    warehouseId               int                                null,
    warehouseName             varchar(100)                       null,
    warehouseType             varchar(100)                       null
);

create index idx_sku
    on openapi_inventory_full (sku);

-- auto-generated definition
create table openapi_lotno_detail_full
(
    id                     int auto_increment
        primary key,
    createdAt              datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    fid                    int                                null,
    purchaseCode           varchar(100)                       null,
    returnQuantity         int                                null,
    excludeTaxPrice        decimal(15, 5)                     null,
    fnsku                  varchar(100)                       null,
    qcStatus               varchar(100)                       null,
    singleQuantity         int                                null,
    packageWeight          double                             null,
    volumeWeight           double                             null,
    productName            varchar(100)                       null,
    flQuantity             int                                null,
    recentWarehousingDate  datetime                           null,
    poItemId               int                                null,
    adjustmentQuantity     int                                null,
    actualTotalPriceAmount json                               null,
    productTypeName        varchar(100)                       null,
    invoiceType            varchar(100)                       null,
    warehousingDate        datetime                           null,
    excludeTaxPriceAmount  json                               null,
    brand                  varchar(100)                       null,
    deliveryFlag           tinyint(1)                         null,
    receiveMemo            varchar(100)                       null,
    taxFlag                tinyint(1)                         null,
    arrivalWarehouseId     varchar(100)                       null,
    dlCode                 varchar(100)                       null,
    warehousingQuantity    int                                null,
    giftFlag               tinyint(1)                         null,
    expectDeliveryDate     date                               null,
    poBalanceQuantity      int                                null,
    deliveryWarehouseId    varchar(100)                       null,
    listingTitle           varchar(500)                       null,
    actualTotalPrice       decimal(15, 5)                     null,
    invoiceTaxRate         double                             null,
    taxRebateRate          double                             null,
    deliveryWarehouseName  varchar(100)                       null,
    taxRate                double                             null,
    warehousingPriceAmount json                               null,
    unit                   varchar(100)                       null,
    assemblyName           varchar(100)                       null,
    transferWarehouseId    varchar(100)                       null,
    creater                varchar(100)                       null,
    qcStatusName           varchar(100)                       null,
    invoiceTypeName        varchar(100)                       null,
    code                   varchar(100)                       null,
    inboundCode            varchar(100)                       null,
    listingLevel           varchar(100)                       null,
    supplierCode           varchar(100)                       null,
    packedQuantity         int                                null,
    categoryName           varchar(100)                       null,
    customCode             varchar(100)                       null,
    qcReturnQuantity       int                                null,
    inboundWarehouseId     varchar(100)                       null,
    overReceiveFlag        tinyint(1)                         null,
    poCode                 varchar(100)                       null,
    assembly               tinyint(1)                         null,
    shippedQuantity        int                                null,
    procurementMethod      varchar(100)                       null,
    deliveryQuantity       int                                null,
    currency               varchar(10)                        null,
    sellerSku              varchar(100)                       null,
    warehousingPrice       decimal(15, 5)                     null,
    qcFinishDate           date                               null,
    arrivalMarketId        varchar(100)                       null,
    productType            varchar(100)                       null,
    supplierName           varchar(100)                       null,
    transferWarehouseName  varchar(100)                       null,
    inboundWarehouseIdName varchar(100)                       null,
    product                varchar(100)                       null,
    quantity               int                                null,
    drawbackTaxPrice       decimal(15, 5)                     null,
    packagePrice           decimal(15, 5)                     null,
    arrivePriceAmount      json                               null,
    transport              varchar(100)                       null,
    deliveryMemo           varchar(100)                       null,
    planCode               varchar(100)                       null,
    arrivalWarehouseName   varchar(100)                       null,
    arrivePrice            decimal(15, 5)                     null,
    deliveryWarehouse      varchar(100)                       null,
    shipmentId             varchar(100)                       null,
    invoiceExcludetaxPrice decimal(15, 5)                     null,
    asin                   varchar(100)                       null,
    category               varchar(100)                       null,
    listingState           varchar(100)                       null
);

create index idx_code
    on openapi_lotno_detail_full (code);

create index idx_sku
    on openapi_lotno_detail_full (sellerSku);

-- auto-generated definition
create table openapi_lotno_full
(
    id                             int auto_increment
        primary key,
    createdAt                      datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    fid                            varchar(100)                       null,
    qcType                         int                                null,
    reviewerId                     varchar(100)                       null,
    qcStatus                       varchar(100)                       null,
    expectQcDate                   varchar(100)                       null,
    memo                           varchar(100)                       null,
    totalWarehousingQuantity       int                                null,
    domesticLogisticsCostAmountObj json                               null,
    warehousingAmountObj           json                               null,
    erpCreatedAt                   datetime                           null,
    deliveryAmountObj              varchar(100)                       null,
    lotnoItemVOList                json                               null,
    warehousingDate                date                               null,
    qcWay                          varchar(100)                       null,
    auditStatusName                varchar(100)                       null,
    quickInboundCreateFlag         tinyint(1)                         null,
    deliveryCode                   varchar(100)                       null,
    arrivalWarehouseId             varchar(100)                       null,
    dlCode                         varchar(100)                       null,
    warehousingQuantity            int                                null,
    arrivalSupplierId              varchar(100)                       null,
    deliveryWarehouseId            varchar(100)                       null,
    totalDeliveryQuantity          int                                null,
    totalValueAmountObj            json                               null,
    totalValueWarehousingAmount    decimal(15, 5)                     null,
    packages                       int                                null,
    supervisorId                   varchar(100)                       null,
    deliveryWarehouseName          varchar(100)                       null,
    transferName                   varchar(100)                       null,
    transfer                       varchar(100)                       null,
    transferWarehouseId            varchar(100)                       null,
    lotNoState                     int                                null,
    creater                        varchar(100)                       null,
    warehouseType                  varchar(100)                       null,
    needQc                         tinyint(1)                         null,
    qcStatusName                   varchar(100)                       null,
    reviewTime                     datetime                           null,
    supervisorName                 varchar(100)                       null,
    code                           varchar(100)                       null,
    purchaseSubjectName            varchar(100)                       null,
    asCode                         varchar(100)                       null,
    inboundCode                    varchar(100)                       null,
    totalValueWarehousingAmountObj json                               null,
    purchaseBudgetFinanceV2        decimal(15, 5)                     null,
    deliveryAmount                 decimal(15, 5)                     null,
    supplierCode                   varchar(100)                       null,
    deliveryDetailsVoList          json                               null,
    paymentType                    int                                null,
    purchaseType                   int                                null,
    attachmentVOList               json                               null,
    otherBizCode                   varchar(100)                       null,
    arrivalMarketName              varchar(100)                       null,
    domesticLogisticsDetailsList   json                               null,
    isEntryBudgetFinance           tinyint(1)                         null,
    poCode                         varchar(100)                       null,
    procurementMethod              varchar(100)                       null,
    deliveryQuantity               int                                null,
    currency                       varchar(10)                        null,
    shipmentDate                   date                               null,
    domesticLogisticsCost          decimal(15, 5)                     null,
    arrivalMarketId                varchar(100)                       null,
    deliveryDate                   date                               null,
    skuSpecies                     int                                null,
    procureWay                     varchar(100)                       null,
    supplierName                   varchar(100)                       null,
    dlCodes                        json                               null,
    transferWarehouseName          varchar(100)                       null,
    inboundDetailsVoList           json                               null,
    quantity                       int                                null,
    logsList                       json                               null,
    pocCode                        varchar(100)                       null,
    purchaseTypeName               varchar(100)                       null,
    paymentTypeName                varchar(100)                       null,
    deliveryType                   varchar(100)                       null,
    updateTime                     datetime                           null,
    lotNoStateName                 varchar(100)                       null,
    reviewer                       varchar(100)                       null,
    isQc                           tinyint(1)                         null,
    totalVolumeWeight              double                             null,
    warehousingAmount              decimal(15, 5)                     null,
    arrivalWarehouseName           varchar(100)                       null,
    totalValueAmount               decimal(15, 5)                     null,
    isDelivery                     tinyint(1)                         null,
    shipmentIds                    json                               null,
    qcWayName                      varchar(100)                       null,
    flCode                         varchar(100)                       null,
    createTime                     datetime                           null,
    purchaseSubjectId              varchar(100)                       null,
    auditStatus                    int                                null,
    qcCode                         varchar(100)                       null,
    totalPackageWeight             double                             null,
    qcTypeName                     varchar(100)                       null,
    customPoCode                   varchar(100)                       null
)
    collate = utf8mb4_bin;

create index idx_code
    on openapi_lotno_full (code);

-- auto-generated definition
create table openapi_procure_detail_full
(
    id                           int auto_increment
        primary key,
    createdAt                    datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    fid                          varchar(100)                       null,
    responsibilityStr            varchar(100)                       null,
    singleQuantity               int                                null,
    packageWeight                float                              null,
    memo                         varchar(100)                       null,
    balanceQuantity              int                                null,
    volumeWeight                 decimal(15, 5)                     null,
    businessOrderStatus          varchar(100)                       null,
    productName                  varchar(100)                       null,
    orderQuantity                int                                null,
    purchaseUrl                  varchar(1000)                      null,
    businessCode                 varchar(100)                       null,
    giftQuantity                 int                                null,
    afterTaxRebatePrice          decimal(15, 5)                     null,
    reduceQuantity               int                                null,
    excludeTaxPriceAmount        json                               null,
    state                        varchar(100)                       null,
    brand                        varchar(100)                       null,
    changeTypeName               varchar(100)                       null,
    finalTotalAmount             decimal(15, 5)                     null,
    deliveryFlag                 tinyint(1)                         null,
    requirementFrom              varchar(100)                       null,
    planSources                  varchar(100)                       null,
    taxFlag                      tinyint(1)                         null,
    unInboundQuantity            int                                null,
    giftFlag                     tinyint(1)                         null,
    includePackageName           varchar(100)                       null,
    invoiceExcludetaxPriceAmount json                               null,
    plCreater                    varchar(100)                       null,
    taxRebateAmount              decimal(15, 5)                     null,
    packages                     varchar(100)                       null,
    transferWarehouseId          varchar(100)                       null,
    listingTitlePrint            varchar(1000)                      null,
    estimateBox                  varchar(100)                       null,
    totalTaxRebateAmountObj      json                               null,
    invoiceTypeName              varchar(100)                       null,
    planIds                      varchar(500)                       null,
    taxRebateAmountObj           json                               null,
    isFbaWarehouse               tinyint(1)                         null,
    productNamePrint             varchar(1000)                      null,
    actualPrice                  decimal(15, 5)                     null,
    supplierNumber               varchar(100)                       null,
    listingLevel                 varchar(100)                       null,
    totalActualAmount            decimal(15, 5)                     null,
    supplierCode                 varchar(100)                       null,
    splitItems                   json                               null,
    totalActualAmountObj         json                               null,
    barcodeDescription           varchar(100)                       null,
    packageRule                  varchar(100)                       null,
    customCode                   varchar(100)                       null,
    businessOrderStatusName      varchar(100)                       null,
    arrivalMarketName            varchar(100)                       null,
    responsibility               varchar(100)                       null,
    overReceiveFlag              tinyint(1)                         null,
    assembly                     varchar(100)                       null,
    currency                     varchar(10)                        null,
    arrivalMarketId              varchar(100)                       null,
    urgent                       tinyint(1)                         null,
    transferWarehouseName        varchar(100)                       null,
    actualDeliveryDate           varchar(100)                       null,
    product                      varchar(100)                       null,
    drawbackTaxPrice             decimal(15, 5)                     null,
    assemblySite                 varchar(100)                       null,
    planQuantity                 int                                null,
    balanceAmount                decimal(15, 5)                     null,
    totalVolumeWeight            varchar(100)                       null,
    arrivalWarehouseName         varchar(100)                       null,
    totalVolume                  varchar(100)                       null,
    transportName                varchar(100)                       null,
    excludeTaxPrice              decimal(15, 5)                     null,
    fnsku                        varchar(100)                       null,
    erpCreatedAt                 varchar(100)                       null,
    totalTaxRebateAmount         decimal(15, 5)                     null,
    actualQuantity               int                                null,
    isDelayDelivery              tinyint(1)                         null,
    productTypeName              varchar(100)                       null,
    invoiceType                  varchar(100)                       null,
    totalAfterTaxRebateAmountObj json                               null,
    arrivalWarehouseId           varchar(100)                       null,
    expectDeliveryDate           varchar(100)                       null,
    totalExcludeTaxAmountObj     json                               null,
    deliveryWarehouseId          varchar(100)                       null,
    listingTitle                 varchar(1000)                      null,
    inboundQuantity              int                                null,
    totalExcludeTaxAmount        decimal(15, 5)                     null,
    invoiceTaxRate               double                             null,
    taxRebateRate                double                             null,
    deliveryWarehouseName        varchar(100)                       null,
    volume                       double                             null,
    totalAmount                  decimal(15, 5)                     null,
    taxRate                      double                             null,
    unit                         varchar(100)                       null,
    planExpectDeliveryDate       varchar(100)                       null,
    childSources                 varchar(100)                       null,
    ids                          json                               null,
    planMarketName               varchar(100)                       null,
    inboundAmount                decimal(15, 5)                     null,
    delayExpectDeliveryDateStr   varchar(100)                       null,
    planMarketId                 varchar(100)                       null,
    deliveryDateChangeMemo       varchar(100)                       null,
    code                         varchar(100)                       null,
    plAssembleParent             varchar(100)                       null,
    assemblyJson                 json                               null,
    categoryName                 varchar(100)                       null,
    includePackage               varchar(100)                       null,
    purchaseType                 varchar(100)                       null,
    giftId                       varchar(100)                       null,
    originId                     varchar(100)                       null,
    lotNoCode                    varchar(100)                       null,
    poCode                       varchar(100)                       null,
    unInboundAmount              decimal(15, 5)                     null,
    supplierSkuRemark            varchar(100)                       null,
    unInboundAmountObj           json                               null,
    increaseQuantity             int                                null,
    changeArrivalWarehouse       varchar(100)                       null,
    sellerSku                    varchar(100)                       null,
    changeItems                  varchar(100)                       null,
    productType                  int                                null,
    supplierName                 varchar(100)                       null,
    assembleRule                 varchar(100)                       null,
    quantity                     int                                null,
    giftFlagStr                  varchar(100)                       null,
    arrivalHouseNameAndMarket    varchar(100)                       null,
    changeReason                 varchar(100)                       null,
    changeDeliveryWarehouse      varchar(100)                       null,
    afterTaxRebatePriceAmount    json                               null,
    purchaseTypeName             varchar(100)                       null,
    taxPriceAmount               json                               null,
    finalOrderQuantity           int                                null,
    changeType                   varchar(100)                       null,
    packagePrice                 decimal(15, 5)                     null,
    specification                varchar(1000)                      null,
    totalAfterTaxRebateAmount    decimal(15, 5)                     null,
    transport                    varchar(100)                       null,
    totalAmountObj               json                               null,
    balanceAmountObj             json                               null,
    inboundAmountObj             json                               null,
    finalTotalAmountObj          json                               null,
    delayExpectDeliveryDate      varchar(100)                       null,
    invoiceExcludetaxPrice       decimal(15, 5)                     null,
    taxPrice                     decimal(15, 5)                     null,
    totalExcludeTax              decimal(15, 5)                     null,
    asin                         varchar(100)                       null,
    category                     varchar(100)                       null,
    totalPackageWeight           double                             null,
    actualPriceAmount            json                               null,
    listingState                 varchar(100)                       null,
    attachmentVOList             json                               null
);

create index idx_code
    on openapi_procure_detail_full (code);

create index idx_poCode
    on openapi_procure_detail_full (poCode);

create index idx_sellerSku
    on openapi_procure_detail_full (sellerSku);

-- auto-generated definition
create table openapi_procure_full
(
    id                           int auto_increment
        primary key,
    createdAt                    datetime default CURRENT_TIMESTAMP not null comment '爬取 ERP 数据的日期，以`日`为单位',
    parentTotalQuantity          int                                null,
    reviewerId                   int                                null,
    totalPackages                int                                null,
    memo                         varchar(1000)                      null,
    businessOrderStatus          varchar(100)                       null,
    productName                  varchar(1000)                      null,
    childInboundQuantity         int                                null,
    businessCode                 varchar(100)                       null,
    totalQuantity                int                                null,
    purchaseOtherFee             decimal(15, 5)                     null,
    undeliveredAmountObj         json                               null,
    businessOrderOrigin          varchar(100)                       null,
    uninboundAmount              varchar(100)                       null,
    reduceQuantity               int                                null,
    invoicesStatusName           varchar(100)                       null,
    taxFlag                      tinyint(1)                         null,
    invoicesStatus               int                                null,
    unInboundQuantity            int                                null,
    paymentRate                  float                              null,
    undeliveredAmount            varchar(100)                       null,
    paymentAmountObj             json                               null,
    terminatedMemo               varchar(100)                       null,
    supervisorId                 int                                null,
    transferWarehouseId          int                                null,
    totalTaxRebateAmountObj      json                               null,
    paymentStatusStr             varchar(100)                       null,
    childTotalQuantity           int                                null,
    deliveryStatus               varchar(100)                       null,
    uninboundAmountObj           json                               null,
    applyStatusStr               varchar(100)                       null,
    actualPrice                  decimal(15, 5)                     null,
    reduceMemo                   varchar(100)                       null,
    supplierNumber               varchar(100)                       null,
    supplierCode                 varchar(100)                       null,
    paymentType                  int                                null,
    customCode                   varchar(100)                       null,
    products                     json                               null,
    businessOrderStatusName      varchar(100)                       null,
    arrivalMarketName            varchar(100)                       null,
    orderTotalAmount             varchar(100)                       null,
    procurementMethod            varchar(100)                       null,
    paymentCycle                 varchar(100)                       null,
    currency                     varchar(10)                        null,
    purchasePlanCode             varchar(100)                       null,
    arrivalMarketId              varchar(100)                       null,
    urgent                       varchar(100)                       null,
    skuSpecies                   int                                null,
    transferWarehouseName        varchar(100)                       null,
    creator                      varchar(100)                       null,
    product                      varchar(100)                       null,
    actualAmount                 varchar(100)                       null,
    updateTime                   varchar(100)                       null,
    appliedAmount                varchar(100)                       null,
    reviewer                     varchar(100)                       null,
    arrivalWarehouseName         varchar(100)                       null,
    createTime                   varchar(100)                       null,
    childActualQuantity          varchar(100)                       null,
    transportName                varchar(100)                       null,
    fnsku                        varchar(100)                       null,
    actualAmountObj              json                               null,
    mergedFlag                   varchar(100)                       null,
    totalTaxRebateAmount         varchar(100)                       null,
    erpCreatedAt                 varchar(100)                       null,
    isBack                       tinyint(1)                         null,
    actualQuantity               int                                null,
    paymentRuleCode              varchar(100)                       null,
    purchaseOtherFeeObj          json                               null,
    increaseMemo                 varchar(100)                       null,
    ordeQuantity                 int                                null,
    paymentDesc                  varchar(100)                       null,
    totalAfterTaxRebateAmountObj json                               null,
    orderTotalAmountObj          json                               null,
    arrivalWarehouseId           varchar(100)                       null,
    expectDeliveryDate           varchar(100)                       null,
    deliveryWarehouseId          varchar(100)                       null,
    inboundQuantity              int                                null,
    financeStatusName            varchar(100)                       null,
    planExpectDeliveryDate       varchar(100)                       null,
    rollbackMemo                 varchar(100)                       null,
    inboundAmount                varchar(100)                       null,
    applyStatus                  varchar(100)                       null,
    supervisor                   varchar(100)                       null,
    reviewTime                   varchar(100)                       null,
    excludeTaxAmountObj          json                               null,
    financeStatus                varchar(100)                       null,
    paymentRuleExpireDateType    varchar(100)                       null,
    code                         varchar(100)                       null,
    purchaseSubjectName          varchar(100)                       null,
    creatorId                    varchar(100)                       null,
    purchaseAmountObj            json                               null,
    procureItemViewVo            varchar(100)                       null,
    paymentAmount                varchar(100)                       null,
    purchaseType                 int                                null,
    lotNoCode                    varchar(1000)                      null,
    unActualQuantity             int                                null,
    paymentRuleVersion           varchar(100)                       null,
    increaseQuantity             int                                null,
    appliedAmountObj             json                               null,
    sellerSku                    varchar(100)                       null,
    productType                  varchar(100)                       null,
    paymentStatus                varchar(100)                       null,
    supplierName                 varchar(100)                       null,
    procurementMethodName        varchar(100)                       null,
    procureItemVoList            json                               null,
    parentActualQuantity         int                                null,
    changeReason                 varchar(100)                       null,
    assembleSkuOrder             tinyint(1)                         null,
    plCreator                    varchar(100)                       null,
    purchaseTypeName             varchar(100)                       null,
    paymentTypeName              varchar(100)                       null,
    totalAfterTaxRebateAmount    varchar(100)                       null,
    excludeTaxAmount             varchar(100)                       null,
    transport                    varchar(100)                       null,
    purchaseAmount               varchar(100)                       null,
    deliveryStatusName           varchar(100)                       null,
    inboundAmountObj             json                               null,
    srmWorkflowDTO               varchar(100)                       null,
    purchaseSubjectId            varchar(100)                       null,
    delayExpectDeliveryDate      varchar(100)                       null,
    asin                         varchar(100)                       null,
    parentInboundQuantity        int                                null,
    paymentDate                  varchar(100)                       null,
    totalPackageWeight           varchar(100)                       null
);

create index idx_code
    on openapi_procure_full (code);

